name: Build Flutter APK

on:
  push:
    branches:
      - main  # se ejecutará cuando subas algo al main
  workflow_dispatch: # permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # o la versión que uses

      - name: Obtener dependencias
        run: flutter pub get

      - name: Construir APK release
        run: flutter build apk --release

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
